# copy this into ../local/ and begin defining your certificates ;)
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: domain-com
  namespace: default
spec:
  secretName: domain-com
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-staging
  commonName: '*.domain.com'
  dnsNames:
    - "*.domain.com"
    - "domain.com"

