apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: ${EMAIL_ADDRESS}

    privateKeySecretRef:
      name: letsencrypt-staging

    solvers:
      - selector: {}
        dns01:
          cloudflare:
            email: ${EMAIL_ADDRESS}
            apiKeySecretRef:
              name: cloudflare-api
              key: api-key

