## Helm values for stable/mysql

image: mysql
imageTag: 8

## Specify password for root user
##
## Default: random 10 character string
# mysqlRootPassword: testing

## Create a database user
##
# mysqlUser:
## Default: random 10 character string
# mysqlPassword:

## Create a database
##
# mysqlDatabase:

## Additionnal arguments that are passed to the MySQL container.
## For example use --default-authentication-plugin=mysql_native_password if older clients need to
## connect to a MySQL 8 instance.
args: ['--default-authentication-plugin=mysql_native_password']
#args: ['/bin/bash', '-c', 'while true; do sleep 100; done']

extraVolumes: |
  # - name: extras
  #   emptyDir: {}
extraVolumeMounts: |
  # - name: extras
  #   mountPath: /usr/share/extras
  #   readOnly: true
extraInitContainers: |
  # - name: do-something
  #   image: busybox
  #   command: ['do', 'something']

# Use the `mysql` secret
existingSecret: "mysql"

## Persist data to a persistent volume
persistence:
  enabled: true
  existingClaim: nebula-mysql-data

## Configure resource requests and limits
resources:
  requests:
    memory: 256Mi
    cpu: 100m

livenessProbe:
  initialDelaySeconds: 120
  periodSeconds: 30
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3

readinessProbe:
  initialDelaySeconds: 50
  periodSeconds: 30
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3

# Custom mysql configuration files used to override default mysql settings
configurationFiles:
  mysql.cnf: |-
    [mysqld]
    skip-name-resolve
    default-authentication-plugin=mysql_native_password
    innodb_log_checksums=ON
    # innodb_force_recovery=1

initializationFiles: {}

## Configure the service
service:
  annotations: {}
  type: ClusterIP
  port: 3306

# Deployment Annotations
deploymentAnnotations: {}

# To be added to the database server pod(s)
podAnnotations: {}
podLabels: {}

## Set pod priorityClassName
# priorityClassName: {}

## Init container resources defaults
initContainer:
  resources:
    requests:
      memory: 10Mi
      cpu: 10m

