# Copy as `volumes.local.yaml` and adapt to your needs
---
# Definition of the volumes and claims used for seafile
apiVersion: v1
kind: PersistentVolume
metadata:
  name: seafile-local-storage
spec:
  capacity:
    storage: 500Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    # TODO: local storage path
    path: /media/storage/seafile
  claimRef:
    namespace: default
    name: seafile-local-storage
  # nodeAffinity:  # TODO: bind to a specific node
  #   required:
  #     nodeSelectorTerms:
  #       - matchExpressions:
  #           - key: kubernetes.io/hostname
  #             operator: In
  #             values:
  #               - my-nas
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seafile-local-storage
  namespace: default
spec:
  storageClassName: "local-storage"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi

