# ingress-nginx default values
# https://github.com/kubernetes/ingress-nginx/blob/master/charts/ingress-nginx/values.yaml
controller:

  ## The name of the Ingress controller daemonset or deployment.
  name: frontend

  ## Use a daemonset (because we're opening HTTP[S] ports on the host namespace)
  kind: DaemonSet

  ## K8S doesn't allow low ports to be used, so we workaround
  hostNetwork: true

  # custom configuration options https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/
  config: {}

  #extraArgs:
  #   default-ssl-certificate: "<namespace>/<secret_name>"

  ## The node selector for pod assignment for the Ingress controller pods.
  nodeSelector: {}

  ## The affinity of the Ingress controller pods.
  affinity: {}

  ## The number of replicas of the Ingress controller deployment.
  replicaCount: 1

  service:
    enabled: true
    ## The type of service to create for the Ingress controller.
    type: NodePort
    ## The value Local preserves the client source IP.
    externalTrafficPolicy: Local
    ## The annotations of the Ingress controller service.
    annotations: {}
    ## The name of the service
    ## Autogenerated if not set or set to "".
    name: frontend

