write-kubeconfig-mode: "0644"
service-node-port-range: '20000-40000'
kubelet-arg: 'config=/etc/rancher/k3s/kubelet-config.yaml'
disable:
  - "traefik"
tls-san:
  - "nebula.local"
node-label:
  - "nas/role=primary"
