apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration

allowedUnsafeSysctls:
  - 'net.ipv4.ip_unprivileged_port_start'

failSwapOn: false
featureGates:
  NodeSwap: true
memorySwap:
  swapBehavior: UnlimitedSwap

